stores:
    desktop:
        hyprland:
            target: /home/cush/.config/hypr
        quickshell:
            target: /home/cush/.config/quickshell
        rofi:
            target: /home/cush/.config/rofi/
        waybar:
            target: /home/cush/.config/waybar
    editors:
        neovim:
            target: /home/cush/.config/nvim
    fonts:
        fontconfig:
            target: ~/.config/fontconfig
    kmonad:
        target: /home/cush/.config/kmonad
    shells:
        fish:
            target: /home/cush/.config/fish/
        nushell:
            target: /home/cush/.config/nushell
    terminals:
        ghostty:
            target: /home/cush/.config/ghostty
        tmux:
            target: /home/cush/.config/tmux
    tools:
        btop:
            target: ~/.config/btop
        gh:
            target: ~/.config/gh
            files:
                - config.yml
        glow:
            target: ~/.config/glow
        htop:
            target: ~/.config/htop
        lazygit:
            target: ~/.config/lazygit
        mise:
            target: ~/.config/mise
