stores:
    shells/fish:
        target: /home/cush/.config/fish/
    ghostty:
        target: /home/cush/.config/ghostty
    hyprland:
        target: /home/cush/.config/hypr
    kmonad:
        target: /home/cush/.config/kmonad
    neovim:
        target: /home/cush/.config/nvim
    nushell:
        target: /home/cush/.config/nushell
    quickshell:
        target: /home/cush/.config/quickshell
    rofi:
        target: /home/cush/.config/rofi/
    tmux:
        target: /home/cush/.config/tmux
    waybar:
        target: /home/cush/.config/waybar
