return {
	"abecodes/tabout.nvim",
	lazy = false,
	event = "InsertCharPre",
	priority = 1000,
	dependencies = {
		"nvim-treesitter/nvim-treesitter",
	},
	opts = {
		tabkey = "<Tab>",
		backwards_tabkey = "<S-Tab>",
		act_as_tab = true,
		ast_as_shift_tab = true,
		default_tab = "<C-t>",
		default_shift_tab = "<C-d>",
		enable_backwards = true,
		completion = false,
		tabouts = {
			{ open = "'", close = "'" },
			{ open = '"', close = '"' },
			{ open = "`", close = "`" },
			{ open = "(", close = ")" },
			{ open = "[", close = "]" },
			{ open = "{", close = "}" },
			{ open = "<", close = ">" },
		},
		ignore_beginning = true,
		exclude = {},
	},
}
