################
##### MISC #####
################

# https://wiki.hypr.land/Configuring/Variables/#misc
misc {
    force_default_wallpaper = 0 # Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = false # If true disables the random hyprland logo / anime girl background. :(

    # VRR / Adaptive Sync. Requires FreeSync = On in the monitor OSD.
    # 0 = off, 1 = always on, 2 = fullscreen-only (desktop locked, games swing)
    vrr = 2
}

